### ISSUE TITLE
ERROR: For input string: "9223372036854775808"

### ISSUE THREAD

**Issue by schorlton** [bcgsc/RNA-Bloom#43]
Another error which seems to be from too few/too short reads as input? But pretty cryptic. Thanks again!!
```bash
root@633c29844365:/data/retry# rnabloom -outdir rnabloom_out -t 8 -long filtered.fastq -ntcard
RNA-Bloom v1.4.3
args: [-outdir, rnabloom_out, -t, 8, -long, filtered.fastq, -ntcard]

name:   rnabloom
outdir: rnabloom_out
WARNING: Output directory does not exist!
Created output directory at `rnabloom_out`

K-mer counting with ntCard...
Running command: `ntcard -t 8 -k 17 -c 65535 -p rnabloom_out/rnabloom @rnabloom_out/rnabloom.ntcard.readslist.txt`...
Parsing histogram file `rnabloom_out/rnabloom_k17.hist`...
ERROR: For input string: "9223372036854775808"
java.lang.NumberFormatException: For input string: "9223372036854775808"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Long.parseLong(Long.java:696)
        at java.base/java.lang.Long.parseLong(Long.java:817)
        at rnabloom.util.NTCardHistogram.<init>(NTCardHistogram.java:44)
        at rnabloom.RNABloom.getNTCardHistogram(RNABloom.java:5568)
        at rnabloom.RNABloom.main(RNABloom.java:6631)
```

- [ ] version of RNA-Bloom with `java -jar RNA-Bloom.jar -version`
- [x] version of java with `java -version`
```bash
root@633c29844365:/data/retry# java --version
openjdk 11.0.9.1-internal 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1-internal+0-adhoc..src)
OpenJDK 64-Bit Server VM (build 11.0.9.1-internal+0-adhoc..src, mixed mode)
```
- [ ] exact command used to run RNA-Bloom

**Comment by kmnip** [comment]
Can you please print the first few lines of `rnabloom_k17.hist`? e.g.

```
head rnabloom_out/rnabloom_k17.hist
```

**Comment by kmnip** [comment]
This number `9223372036854775808` is just larger than the largest 64-bit long integer in Java, i.e. `9,223,372,036,854,775,807`.

Can you please report your ntCard version?
```
ntcard --version
```

**Comment by schorlton** [comment]
```bash
>ntcard --version
ntCard 1.2.2
```

```bash
>head rnabloom_out/rnabloom_k17.hist 
F1      270
F0      0
1       9223372036854775808
2       9223372036854775808
3       9223372036854775808
4       9223372036854775808
5       9223372036854775808
6       9223372036854775808
7       9223372036854775808
8       9223372036854775808
```

**Comment by kmnip** [comment]
This looks like a bug in ntCard. Can you share your read sequences with me?

**Comment by schorlton** [comment]
Done! Emailed kmnip@bcgsc.ca. Let me know if you need it to be sent somewhere else.

**Comment by kmnip** [comment]
Thanks, I got your email and I was able to replicate the same issue.
I created an issue for this in ntCard:
https://github.com/bcgsc/ntCard/issues/73
