### ISSUE TITLE
null exception

### ISSUE THREAD

**Issue by dschwoerer** [bcgsc/RNA-Bloom#9]
Hi, I have been trying to run `java -jar RNA-Bloom.jar -stage 3 -long data.fastq -ref Arabidopsis_thaliana.TAIR10.47.gtf -o ${path}` with java 11, but that fails with the following output:

```
> Stage 1: Construct graph from reads (k=17)
[1] Parsing ${path}/sra_2_data.fastq...
Parsed 490,413 reads in total.
Augmenting graph with reference transcripts...
[2] Parsing ${path}/Arabidopsis_thaliana.TAIR10.47.gtf...
DBG Bloom filter FPR:                 1.3991246 %
Counting Bloom filter FPR:            0.06179431 %
> Stage 1 completed in 55.178s

> Stage 2: Correct long reads for "rnabloom"
Parsing ${path}/sra_2_data.fastq...
Corrected Read Lengths Sampling Distribution (n=1000)
  min  q1  med  q3  max
  202  401  923  1847  10000
ERROR: null
java.util.NoSuchElementException
  at rnabloom.io.FastxSequenceIterator.nextWithName(FastxSequenceIterator.java:94)
  at rnabloom.RNABloom.correctLongReadsMultithreaded(RNABloom.java:3412)
  at rnabloom.RNABloom.correctLongReads(RNABloom.java:4498)
  at rnabloom.RNABloom.main(RNABloom.java:6264)
```

I noticed it creates the file `rnabloom.longreads.corrected.short.fa` but the file is empty.

I tried also to run with java8, but then it gets stuck here:
```
> Stage 2: Correct long reads for "rnabloom"
Parsing ${path}/sra_2_data.fastq...
```
Not sure what it is doing but is using 12 threads, but only 3 to 4% cpu

**Comment by kmnip** [comment]
The `-ref` option expects a FASTA file and it only works with short read assembly only.

**Comment by kmnip** [comment]
Which version are you using?

**Comment by dschwoerer** [comment]
That is the 1.3.1 release. Yes the, *.fa file is a fasta file, so should be fine.

[The docs](https://github.com/bcgsc/RNA-Bloom#c-assemble-nanopore-direct-rna-sequencing-data) mention that it should work with long reads. I tried without a reference genome, but got the same error.

**Comment by kmnip** [comment]
Several things don't add up here.

1. The RNA-Bloom command you reported (in the first message) did not use `-t 12`. I don't see how it would be using 12 threads.

2. The stack trace of the exception you reported (in the first message) indicates that you are not using version 1.3.1 of RNA-Bloom. For example, `RNABloom.java:3412` is an empty line and won't be able to throw an exception.

3. You mentioned that you have FASTA file, but the log indicates that you have FASTQ reads and a GTF file was supplied to the `-ref` option. Again, the `-ref` option only works with short-read assembly and it takes in a reference transcriptome FASTA, as described in the README.

I downloaded RNA-Bloom version 1.3.1 and I can't reproduce your error with my test reads and Java 11.

My test nanopore read file simulated with NanoSim (215 MB, 442,245 reads):
https://www.bcgsc.ca/downloads/supplementary/rnabloom/nanosim_mouse_rna.fa.gz

RNA-Bloom options I used:
`-t 12 -ntcard -outdir OUTDIR -long READS`

My output log:
https://www.bcgsc.ca/downloads/supplementary/rnabloom/nanosim_mouse_rna_log.txt

Please try this and let me know whether it works for you.
